### ISSUE TITLE
`entry_proc` utilization parts are not added

### ISSUE THREAD

**Issue by furkanmustafa** [Keepco/wine-overwatch-patches#1]
in this patch => [kernel32-read-entry-before-ldrinitializethunk.patch](https://github.com/Keepco/wine-overwatch-patches/blob/master/kernel32-read-entry-before-ldrinitializethunk.patch)

looks like it gets assignment to `entry_proc` but does not use it anywhere.

You might want to check [v2](https://www.winehq.org/pipermail/wine-patches/2017-February/157580.html) or [v2](https://www.winehq.org/pipermail/wine-patches/2017-February/157644.html) for entry point fix.

**Comment by Keepco** [comment]
Thanks, removed v2 and added v3
